### ISSUE TITLE
sdl-gyro.gdextension file needs corrections

### ISSUE THREAD

**Issue by EliteMasterEric** [SagaPDev/Godot-SDL-Gyro#10]
I would have submitted a PR, but from what I can tell, the file is not a part of the repo.

1. File names should be relative, so that the extension can be placed wherever you want for organization.
2. Windows file name needs to be corrected to match the actual path name.

Here's my modified `gdextension` file which has these corrections:

```
[configuration]

entry_symbol = "sdlgyro_library_init"
compatibility_minimum = "4.1"

[libraries]

macos.debug = "libsdlgyro.macos.template_debug.framework"
macos.release = "libsdlgyro.macos.template_release.framework"

windows.debug.x86_32 = "libsdlgyro.windows.template_debug.x86_32.dll"
windows.release.x86_32 = "libsdlgyro.windows.template_release.x86_32.dll"
windows.debug.x86_64 = "libsdlgyro.windows.template_debug.x86_64.dll"
windows.release.x86_64 = "libsdlgyro.windows.template_release.x86_64.dll"

linux.debug.x86_64 = "libsdlgyro.linux.template_debug.x86_64.so"
linux.release.x86_64 = "libsdlgyro.linux.template_release.x86_64.so"
```

**Comment by SagaPDev** [comment]
Thanks, i actually don't know why the windows files were named differently or how it worked last time i check the extension in windows, and making the path relatives seem like a good idea.
Also the file it is actually part of the repo, inside the example project, here are the fixes -> 12f7fe67e95d2b94df44e86cd47aea887cad216b
