### ISSUE TITLE
Not sure what im doing wrong.

### ISSUE THREAD

**Issue by TheGlobalGuest** [SagaPDev/Godot-SDL-Gyro#12]
Hi! 
I've been all over the place looking for a way to do gyrocontrols in godot so i can recreate the tub tilting effect from "Super Rub A Dub". After alot of looking i've come across this github page.

Unfortunately im still inept and haven't done much outside of GDscript so i don't know what i've done wrong when following the guide.

https://github.com/user-attachments/assets/6d6c67a0-c4de-42f2-817d-1dbe0fdfecf6

can i have some help in pointing out where i went wrong? although i do understand if what i gave isn't enough.

**Comment by SagaPDev** [comment]
you seem to have the source code there, (even then i still don't understand why it can't correctly open the add-on from there)
either way [this](https://github.com/SagaPDev/Godot-SDL-Gyro/releases/download/v0.3/godot-sdl-gyro-addon.zip) this is the extension itself you can extract and drop in your project, i think this is what you need, let me know of any this gives you trouble, as you can see, there are still things to iron out

**Comment by TheGlobalGuest** [comment]
I changed the library to the https://github.com/SagaPDev/Godot-SDL-Gyro/commit/12f7fe67e95d2b94df44e86cd47aea887cad216b version (since the other one still gave the "Library not found" error) and it now loads with no errors. but still has some side effects in the way:

1. for some reason there is a loooong wait time when starting 

2. gamepadPoling() and the functions that requre it gives an error

https://github.com/user-attachments/assets/5d4ec7b1-c7c7-47b5-b77d-c60a33596f1c

just as a note, apart from the changes i've shown in both vids the file is unchanged from the github one.

**Comment by TheGlobalGuest** [comment]
I thougth i would drop the current project file here incase im just missing out something.
[gyro stuff copy.zip](https://github.com/user-attachments/files/16547834/gyro.stuff.copy.zip)

**Comment by TheGlobalGuest** [comment]
I tested your exsample project, added the ">|" to the test script and it works now! 

https://github.com/user-attachments/assets/165d7e59-01c6-4003-a942-99528dd03a1c

there is some drift when calibrating but i think thats more because of the dualshock 4 im using (also the loooong loading times is just from the godot version im using)

thank you very much for taking time out of your day to help me! :D
