### ISSUE TITLE
Build Failing on Windows

### ISSUE THREAD

**Issue by SagaPDev** [SagaPDev/Godot-SDL-Gyro#7]
I cannot continue with the compilation of the addon because it does not open SDL2.lib, I don't know what to do

_Originally posted by @ThePhantomMask in https://github.com/SagaPDev/Godot-SDL-Gyro/discussions/6_

**Comment by SagaPDev** [comment]
@ThePhantomMask i  push some small changes to the SConstruct file, the errors you are having leave me to believe that maybe you don't have MinGW installed or scons is not piking your minGW installation.

pull the latest changes to the Sconstruct file, and compile the project with `scons use_mingw=yes -Q` and show me the output to make sure

If this is the case check [here](https://docs.godotengine.org/en/stable/contributing/development/compiling/compiling_for_windows.html#requirements) for ways to install it (in my windows environment i used scoop)

**Comment by ThePhantomMask** [comment]
> @ThePhantomMask i push some small changes to the SConstruct file, the errors you are having leave me to believe that maybe you don't have MinGW installed or scons is not piking your minGW installation.
> 
> pull the latest changes to the Sconstruct file, and compile the project with `scons use_mingw=yes -Q` and show me the output to make sure
> 
> If this is the case check [here](https://docs.godotengine.org/en/stable/contributing/development/compiling/compiling_for_windows.html#requirements) for ways to install it (in my windows environment i used scoop)

It works for me now...thanks for the help
